"""PFC3D -> strain -> Vp -> synthetic seismic, in one command.

Replaces the manual loop: run PFC in the GUI, export a point .vtk, open
ParaView, apply Delaunay3D, save a .vtu, then run the analysis by hand.

    python3 pfc_pipeline.py model.py --stem runs/ss01 --alpha 125 --zmax -100

Stages, each skippable so a failed run can be resumed:

  1. pfc      run `model.py` inside PFC in batch. That script builds and
              cycles the model and calls pfc_export.export() twice --
              once with reference=True on the equilibrated pack, once at
              the end. See pfc_export.py.
  2. mesh     make_mesh.py, Qhull rather than ParaView's Delaunay3D
              (which drops 14.5% of a DEM pack; see that module).
  3. strain   strain_analysis.py -- the full tensor, not just det(F) - 1.
  4. vp       vp_from_strain.py -- Vp, Vs, rho from the volumetric strain
              and the run's own per-particle density.
  5. seismic  seismic_section.py -- velocity sections and the
              1D-convolution synthetic section.

FINDING THE PFC EXECUTABLE. Stage 1 needs to know how to launch PFC in
batch, and that differs across PFC 6/7/8. Pass --pfc-exe, or set
PFC_EXE, or put it in pfc_pipeline.json next to this file. The verified
PFC 6.0 form, which is what ships in pfc_pipeline.json, is:

    {"pfc_exe": "C:/Program Files/Itasca/PFC600/exe64/pfc3d600_console.exe",
     "batch_args": ["{wrapper}"]}

`{script}` substitutes the Python file to run; `{wrapper}` substitutes a
generated one-line .dat that calls it. Use `{wrapper}` on PFC 6: the
console auto-calls the single file it is given, but only when the
extension is one the command processor recognises, so a bare .py loads
and then sits at the `pfc3d>` prompt forever. Extra arguments are
ignored and stdin is not read, which rules out the other obvious forms.
A .dat containing `program call '<script>'` is how PFC's own shipped
examples run Python, and it is what write_wrapper() below emits.

Everything downstream of stage 1 is tested; stage 1 is the part that
depends on your installation.
"""
import argparse
import json
import os
import subprocess
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
CONFIG = os.path.join(HERE, "pfc_pipeline.json")
DEFAULT_BATCH_ARGS = ["{wrapper}"]             # verified on PFC 6.0; see docstring
STAGES = ("pfc", "mesh", "strain", "vp", "seismic")


def load_config():
    if os.path.exists(CONFIG):
        with open(CONFIG) as f:
            return json.load(f)
    return {}


SHIM = '''"""Generated by pfc_pipeline.write_wrapper -- do not edit.

PFC 6.0 runs a Python file by compiling it as an anonymous string, so
inside it __file__ is NOT DEFINED and __name__ is not "__main__". A model
script that locates the repository with os.path.abspath(__file__) dies
with NameError before its first command, and one whose body sits under
`if __name__ == "__main__"` runs nothing at all and looks like a success.
This shim supplies both, and puts the repository on sys.path so the
script's own imports resolve.

It also quits PFC in a finally. An error inside a called file aborts the
rest of the calling .dat -- including its `program quit` -- which leaves
an unattended batch run sitting at the pfc3d> prompt forever.
"""
import sys
import traceback

import itasca as it

ROOT, SCRIPT = r"{root}", r"{script}"
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

try:
    with open(SCRIPT) as fh:
        code = compile(fh.read(), SCRIPT, "exec")
    exec(code, {{"__file__": SCRIPT, "__name__": "__main__"}})
except BaseException:
    traceback.print_exc()
    print("[pfc shim] MODEL SCRIPT FAILED -- traceback above. PFC will still "
          "exit 0; judge the run by whether the exports were written.")
finally:
    sys.stdout.flush()
    it.command("program quit")
'''


def write_wrapper(script, out_dir=None, root=None):
    """Emit the .dat PFC is handed, plus the shim it calls.

    Returns the .dat path. See SHIM above for why the model script is not
    called directly.
    """
    script = os.path.abspath(script)
    root = os.path.abspath(root or HERE)
    out_dir = out_dir or tempfile.gettempdir()
    stem = os.path.join(out_dir,
                        "pfc_run_" + os.path.splitext(os.path.basename(script))[0])

    with open(stem + ".py", "w") as f:
        f.write(SHIM.format(root=root.replace("\\", "/"),
                            script=script.replace("\\", "/")))
    with open(stem + ".dat", "w") as f:
        # forward slashes: PFC reads a backslash as an escape inside a
        # quoted string, so a raw Windows path loses its separators.
        # `suppress` stops PFC echoing the whole file back at us.
        print("program call '%s' suppress" % (stem + ".py").replace("\\", "/"), file=f)
        print("program quit", file=f)
    return stem + ".dat"


def pfc_argv(exe, cfg, script):
    """The full command line that runs `script` inside PFC."""
    args = cfg.get("batch_args", DEFAULT_BATCH_ARGS)
    sub = {"script": os.path.abspath(script)}
    if any("{wrapper}" in a for a in args):
        sub["wrapper"] = write_wrapper(script)
    return [exe] + [a.format(**sub) for a in args]


def run(cmd, label):
    print(f"\n=== {label} ===\n$ {' '.join(map(str, cmd))}", flush=True)
    t0 = time.time()
    r = subprocess.run([str(c) for c in cmd])
    if r.returncode != 0:
        raise SystemExit(f"{label} failed with exit code {r.returncode}")
    print(f"--- {label} done in {time.time() - t0:.0f} s", flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("model", nargs="?",
                    help="the Python file PFC runs (stage 1). Omit with "
                         "--skip pfc to analyse an existing export.")
    ap.add_argument("--stem", required=True,
                    help="path prefix the exports share, e.g. runs/ss01. "
                         "pfc_export writes <stem>_init_pos.txt etc.")
    ap.add_argument("--results", default="results")
    ap.add_argument("--tag", default=None, help="figure suffix; default: the stem's basename")
    ap.add_argument("--alpha", type=float, default=None,
                    help="max tetrahedron edge in m (default: 3x the median "
                         "nearest-neighbour spacing)")
    ap.add_argument("--q-min", type=float, default=0.05)
    ap.add_argument("--zmax", type=float, default=None,
                    help="drop particles above this z, e.g. an unconfined cap")
    ap.add_argument("--freq", type=float, default=25.0)
    ap.add_argument("--dx", type=float, default=20.0)
    ap.add_argument("--pfc-exe", default=None)
    ap.add_argument("--skip", nargs="*", default=[], choices=STAGES)
    ap.add_argument("--only", nargs="*", default=None, choices=STAGES)
    a = ap.parse_args()

    cfg = load_config()
    wanted = [s for s in STAGES if s not in a.skip and (a.only is None or s in a.only)]
    print(f"stages: {', '.join(wanted) if wanted else '(none)'}")

    tag = a.tag or os.path.basename(a.stem)
    os.makedirs(a.results, exist_ok=True)
    init = f"{a.stem}_init_pos.txt"
    pos = f"{a.stem}_pos.txt"
    density = f"{a.stem}_density.txt"
    mesh = f"{a.stem}_mesh.vtu"
    strain_npz = f"{a.results}/strain_{tag}.npz"
    vp_npz = f"{a.results}/vp_{tag}.npz"
    py = sys.executable

    if "pfc" in wanted:
        if not a.model:
            raise SystemExit("stage 'pfc' needs a model script; pass one or --skip pfc")
        exe = a.pfc_exe or os.environ.get("PFC_EXE") or cfg.get("pfc_exe")
        if not exe:
            raise SystemExit(
                "PFC executable not known. Pass --pfc-exe, set PFC_EXE, or write\n"
                f"  {CONFIG}\n"
                '  {"pfc_exe": "...pfc3d700.exe", "batch_args": ["call", "{script}"]}\n'
                "See the module docstring.")
        run(pfc_argv(exe, cfg, a.model), f"1. PFC: {a.model}")
        # PFC quits 0 even when the Python it ran raised, so the exit
        # code proves nothing. The exports existing is the real test.
        for f in (init, pos, density):
            if not os.path.exists(f):
                raise SystemExit(
                    f"PFC finished but {f} is missing. Check that your model "
                    f"script calls pfc_export.export('{a.stem}', reference=True) "
                    f"on the equilibrated pack and pfc_export.export('{a.stem}') "
                    f"at the end.")

    if "mesh" in wanted:
        cmd = [py, f"{HERE}/make_mesh.py", init, mesh, "--q-min", a.q_min]
        if a.alpha:
            cmd += ["--alpha-edge", a.alpha]
        run(cmd, "2. mesh (Qhull)")

    if "strain" in wanted:
        cmd = [py, f"{HERE}/strain_analysis.py", "--init", init, "--pos", pos,
               "--q-min", a.q_min, "--out", strain_npz]
        if a.alpha:
            cmd += ["--alpha", a.alpha]
        if a.zmax is not None:
            cmd += ["--zmax", a.zmax]
        run(cmd, "3. strain tensor")

    if "vp" in wanted:
        cmd = [py, f"{HERE}/vp_from_strain.py", "--init", init, "--pos", pos,
               "--density", density, "--q-min", a.q_min, "--out", vp_npz]
        if a.alpha:
            cmd += ["--alpha", a.alpha]
        if a.zmax is not None:
            cmd += ["--zmax", a.zmax]
        run(cmd, "4. Vp from strain")

    if "seismic" in wanted:
        run([py, f"{HERE}/seismic_section.py", vp_npz, tag,
             "--dx", a.dx, "--freq", a.freq], "5. synthetic seismic")

    print(f"\nall done. figures: fig_seis_{tag}_*.png   arrays: {vp_npz}, {strain_npz}")


if __name__ == "__main__":
    main()
